wandb_version: 1

input_dim:
  desc: null
  value: 8
output_dim:
  desc: null
  value: 1
hidden_dim:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 128
dataset_dir:
  desc: null
  value: dataset
checkpoint_dir:
  desc: null
  value: checkpoints
train_split:
  desc: null
  value: 0.8
valid_split:
  desc: null
  value: 0.2
seed:
  desc: null
  value: 42
num_workers:
  desc: null
  value: 1
weight_decay:
  desc: null
  value: 1.0e-05
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714326746.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 61
      4: 3.11.6
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
